### ISSUE TITLE
Broken links in the README.md file

### ISSUE THREAD

**Issue by Mazzya** [qubic/wallet#16]
I noticed that some links were out of date, so I opened a PR : https://github.com/qubic/wallet/pull/15

**Comment by AndyQus** [comment]
thank you very much

**Comment by Mazzya** [comment]
you're welcome, should i point the pr to the 3.7 branch ?

**Comment by Mazzya** [comment]
Done 👍🏼

**Comment by AndyQus** [comment]
Thanks for your support
