### ISSUE TITLE
Add a direct link to the browser when one of the addresses is clicked in balance section of the wallet

### ISSUE THREAD

**Issue by Mazzya** [qubic/wallet#21]
I think that when a user clicks on an address, whether sending or receiving, they should be redirected to the explorer to view the wallet's assets, e.g. :

From: OYFQKDVYVTAPEDMKFUXFZMEFWCQCUDYKPLYJYRSSAFZSCGHJHFAXTLXCMIDD : 
```
<a href="https://explorer.qubic.org/network/address/OYFQKDVYVTAPEDMKFUXFZMEFWCQCUDYKPLYJYRSSAFZSCGHJHFAXTLXCMIDD">From: OYFQKDVYVTAPEDMKFUXFZMEFWCQCUDYKPLYJYRSSAFZSCGHJHFAXTLXCMIDD</a>
```
And the same goes for the receiver.

It's extremely practical and time-saving.

**Comment by AndyQus** [comment]
All PublicIds already have a copy function. I'll put a redirect icon behind it, I'll see what it looks like.

**Comment by AndyQus** [comment]
PublicId with redirection to explorer in the dashboard and in balance. Layout/design balance updated. Bug fixed in balance.

**Comment by Mazzya** [comment]
Thank's man ! Appreciate it :)

**Comment by AndyQus** [comment]
I added another icon to the dashboard, it opens Explorer.
In the balance there is the icon behind the address.

**Comment by AndyQus** [comment]
I immediately adjusted the design of Balance a bit.
