### ISSUE TITLE
Transaction reported as not sent but sent anyway

### ISSUE THREAD

**Issue by J0ET0M** [qubic/wallet#41]
Can you please verify and fix this user request.
![Screenshot_20240521_105309_Discord](https://github.com/qubic/wallet/assets/107187448/2e0b41af-1fc9-455a-a67c-1cb8ca048697)

**Comment by AndyQus** [comment]
I can't recreate it.

Question for TriggerHappy, In the screenshot I see 2 transactions: 
- both are green and confirmed
- when you carried out the 1st transaction, you received a message below saying that the transaction was not confirmed. correct?
- Have you already seen this transaction under transactions?
- 
Do you sometimes have internet problems? This would be the only possibility that your transaction was sent, but then the network could no longer send you a response.

**Comment by AndyQus** [comment]
Trigger has reported
![grafik](https://github.com/qubic/wallet/assets/157237454/4841d466-cfe9-4ab0-8d33-d39f6fad6fd5)

**Comment by Qubiclover** [comment]
Question for TriggerHappy, In the screenshot I see 2 transactions:

both are green and confirmed
when you carried out the 1st transaction, you received a message below saying that the transaction was not confirmed. correct?
Incorrect, when I submitted the first transaction a Red box appeared with bold red text saying busy try again latter. Then I pressed submit again and both transactions went thru. Hope this helps

**Comment by AndyQus** [comment]
![image](https://github.com/qubic/wallet/assets/157237454/34b16834-a45b-4962-919a-18a7c220f0d3)
Here the same message is displayed twice in two different states. I think it is a wrong display/message in the Catch branch.

**Comment by AndyQus** [comment]
Backend is checked by the developer

**Comment by J0ET0M** [comment]
backend got updated that could cause that issue. please report if not.
