### ISSUE TITLE
Create payment and reveal seed actions are available for watch-only accounts

### ISSUE THREAD

**Issue by AndyQus** [qubic/wallet#54]
![image](https://github.com/user-attachments/assets/3c5ceb41-3f3f-4106-944b-fd78d81f2e32)

**Comment by sallymoc** [comment]
These actions shouldn't be available for watch-only accounts. We don't have the private seed so it's not possible to sign transaction or reveal a non existing value

**Comment by AndyQus** [comment]
![image](https://github.com/user-attachments/assets/54cd1c41-c1cf-4eeb-83a2-4089aebe0137)
