### ISSUE TITLE
"Address Information" dialog doesn't show the name of the address

### ISSUE THREAD

**Issue by AndyQus** [qubic/wallet#55]
![image](https://github.com/user-attachments/assets/1be352f4-9f3a-458f-b1e3-9a23e39b7c14)

**Comment by sallymoc** [comment]
It would be good to shown the name of the address here because the dialog is always shown centered and it's not possible to identify to which account is related

**Comment by AndyQus** [comment]
![image](https://github.com/user-attachments/assets/61835895-0404-4d08-b4d6-09c5d81f661e)

**Comment by AndyQus** [comment]
In the display dialog of the IDs the address alias is displayed in the title
