### ISSUE TITLE
Small suggestions for UI/UX improvements

### ISSUE THREAD

**Issue by sallymoc** [qubic/wallet#58]
Please see the images attached

![addAddress](https://github.com/user-attachments/assets/cb41d29c-a4bc-4459-9dce-996c958c2cc4)

![lockVaultDialogConfirmation](https://github.com/user-attachments/assets/f608f8a5-8048-4a8b-9c4c-0497d1191b9c)
![sendQubic](https://github.com/user-attachments/assets/9e9b24f1-41c4-4d55-b57b-872b6214a23f)
![transactions](https://github.com/user-attachments/assets/f286f703-1f6d-4c4d-856d-47ce6d12b85d)
![image](https://github.com/user-attachments/assets/83c226c6-51bd-40d7-a4b2-ddfbc8733d0e)
![image](https://github.com/user-attachments/assets/038500b0-5b2c-4cdf-aee0-df3d2ede53b9)

**Comment by AndyQus** [comment]
I will tackle the tasks for this week. I will implement them in release/4.8.

**Comment by AndyQus** [comment]
done
