### ISSUE TITLE
Cannot add watch only accounts in Mobile web browser

### ISSUE THREAD

**Issue by icyblob** [qubic/wallet#60]
https://github.com/user-attachments/assets/df89ac48-e598-4eb1-b8e9-28e5d2c7be4b

OS: iOS 17.5
Browser: Safari

**Comment by AndyQus** [comment]
There is a problem with encryption with an empty seed in Safari.
I have now changed this, if it is empty then it is set with "onlywatch".
I will also change this in the library. https://github.com/qubic/ts-vault-library
![image](https://github.com/user-attachments/assets/d0c66cf5-f076-4ef6-ad36-792ee228fefd)

**Comment by AndyQus** [comment]
I don't need to write the change to the ts-vault-library addSeed, there is no addSeed function there.
