### ISSUE TITLE
Watch only address: entering address less than 60 chars, the create button is enabled

### ISSUE THREAD

**Issue by icyblob** [qubic/wallet#61]
Although there is a warning, and there is an error after tapping/clicking the button, but the create button still enabled. It should be disabled and the user is unable to tap/click at this case. This issue is reported by @sallymoc. 

![image](https://github.com/user-attachments/assets/844bbfe4-d391-4ae9-aa28-9576468432b4)

**Comment by sallymoc** [comment]
The error I saw is something different. Please see the video attached

https://github.com/user-attachments/assets/e4e252ec-0c4f-4180-89ba-b5d1e33d07dd
