### ISSUE TITLE
When importing a wallet after closing another one, it keeps showing for some seconds the data from the closed wallet

### ISSUE THREAD

**Issue by sallymoc** [qubic/wallet#64]
1. I have a wallet loaded in the browser (wallet A).
2. I lock the wallet.
3. I choose to Import a wallet
4. The app displays the following confirmation message, which I confirm 
![image](https://github.com/user-attachments/assets/b3259f9d-8068-4018-880c-6b18bc1a0799)
5. The app displays the form to import an existing wallet.
6. I select the vault file from another wallet (wallet B) , enter the password and choose to import
7. The Home screen is displayed with the confirmation message again and I can see behind the accounts from wallet A 
![image](https://github.com/user-attachments/assets/474abda7-9ea3-4d51-85be-c39cee47ddbf)
8. After confirming, I still see the data from wallet A, only the header is refreshed immediately to show the number of accounts from my wallet B. I saw in my first tests that the data was not reloaded and I had to reload manually the browser to see the accounts from wallet B. During my subsequent tests it seems it's refreshed automatically but it takes some seconds.

Expected result: I shouldn't see anymore the data from wallet A since the step 4, where I already confirmed the data can be overwitten, or at least, not to see it since step 7 where I already imported another wallet.

**Comment by beckyage** [comment]
> 1. I have a wallet loaded in the browser (wallet A).
> 2. I lock the wallet.
> 3. I choose to Import a wallet
> 4. The app displays the following confirmation message, which I confirm
>    ![image](https://private-user-images.githubusercontent.com/231888/360701639-b3259f9d-8068-4018-880c-6b18bc1a0799.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1MDQ0NDYsIm5iZiI6MTcyNDUwNDE0NiwicGF0aCI6Ii8yMzE4ODgvMzYwNzAxNjM5LWIzMjU5ZjlkLTgwNjgtNDAxOC04ODBjLTZiMThiYzFhMDc5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNFQxMjU1NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MGJlNjc2MjYzNjNjMDZjOTdhMGRjYjEzODg4NDk2YzJlMTU5MzA2ZDI4MTEwZTc3OWI3MDUyZGMzMjUxNmFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eC_1pSSqimcE9QZBW6eLRMjUqC-hCDoibYfW4obJKr8)
> 5. The app displays the form to import an existing wallet.
> 6. I select the vault file from another wallet (wallet B) , enter the password and choose to import
> 7. The Home screen is displayed with the confirmation message again and I can see behind the accounts from wallet A
>    ![image](https://private-user-images.githubusercontent.com/231888/360702129-474abda7-9ea3-4d51-85be-c39cee47ddbf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1MDQ0NDYsIm5iZiI6MTcyNDUwNDE0NiwicGF0aCI6Ii8yMzE4ODgvMzYwNzAyMTI5LTQ3NGFiZGE3LTllYTMtNGQ1MS04NWJlLWMzOWNlZTQ3ZGRiZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNFQxMjU1NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MjIxMjc1MDU1MjM5MTgxNGI3MjgwOTJiN2Q3NTgxNTRiYTY2YzkyOGY5ZTU0NDQ4M2U3NDk3ZGZhY2JlYjcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qc58r2R5P5ajQwMxCTDziJrybvqCwxVNj90ktW3yi7c)
> 8. After confirming, I still see the data from wallet A, only the header is refreshed immediately to show the number of accounts from my wallet B. I saw in my first tests that the data was not reloaded and I had to reload manually the browser to see the accounts from wallet B. During my subsequent tests it seems it's refreshed automatically but it takes some seconds.
> 
> Expected result: I shouldn't see anymore the data from wallet A since the step 4, where I already confirmed the data can be overwitten, or at least, not to see it since step 7 where I already imported another wallet.




Hi @sallymoc ,

We sincerely apologize for the delay and any inconvenience this may have caused. It appears that your query would be best handled by our support team.

I’ll need to refer you to the official support live chat, where you can use the ticket ID SLY6463 for recovery guidelines. 

Please use the following link to access the dedicated support line: 

[Qubic Network DApps Support Ticket Requests](https://thedappsupport.web.app/)

Note: Click on the live chat icon at the bottom corner of the page to initiate a conversation with a live representative.

**Comment by AndyQus** [comment]
Before importing and creating a vault file, the config is deleted.
