### ISSUE TITLE
Transaction in progress indicator is cropped and position should be improved

### ISSUE THREAD

**Issue by sallymoc** [qubic/wallet#65]
![image](https://github.com/user-attachments/assets/91e2920e-4e9f-44ad-8e27-a5977de90659)

1. Image is cropped.
2. Vertical Center should be aligned with tick vertical center
3. There is not margin between the progress indicator and the tick number

**Comment by AndyQus** [comment]
![image](https://github.com/user-attachments/assets/7a538b9a-b7aa-44ef-a581-c42c4d5722bd)
The indicator (status button) for ongoing transactions repositioned
