### ISSUE TITLE
UI Improvements for transactions by Epoch

### ISSUE THREAD

**Issue by sallymoc** [qubic/wallet#66]
![image](https://github.com/user-attachments/assets/4f6c9e0c-5d5c-41fd-bc7a-b99d13650f6d)

**Comment by AndyQus** [comment]
![image](https://github.com/user-attachments/assets/c4ed31e2-5cfe-451f-8ac1-649c824c3b16)

**Comment by AndyQus** [comment]
![image](https://github.com/user-attachments/assets/f30292ef-27ed-4f0b-87a3-8c5cc6f32ea3)
