### ISSUE TITLE
UI improvements for the Dashboard

### ISSUE THREAD

**Issue by sallymoc** [qubic/wallet#68]
![image](https://github.com/user-attachments/assets/617bee20-041d-4282-93f8-a8a6b4e1dc39)

**Comment by AndyQus** [comment]
![image](https://github.com/user-attachments/assets/1e764fd3-ba6a-431a-aaf8-5a026e79fce2)

**Comment by AndyQus** [comment]
dashboard display addresses alias for mobile phone

**Comment by AndyQus** [comment]
![image](https://github.com/user-attachments/assets/c383470f-47c5-419a-b3e6-6ee4e3cf5a4d)
