### ISSUE TITLE
UI improvements for the arrows to move between epochs in Transactions by Epoch

### ISSUE THREAD

**Issue by sallymoc** [qubic/wallet#69]
![image](https://github.com/user-attachments/assets/4f58a48d-f756-4d8f-8cc3-f87895666df1)

**Comment by AndyQus** [comment]
@sallymoc I think the current implementation is great, the epoch display stays in the same position, if I hide the icon instead of deactivating it, the display jumps.

**Comment by sallymoc** [comment]
Hello @AndyQus. Thank you for your message. I will clarify point by point :)
1. Can we have the buttons in white? It seems they are disabled.
Currently the color is different to the one used in the "123 epoch" in the image. Please if you can use the same. With the gray, in contrast with the text color, it seems they are disabled.
2. Button 1 should decrease the epoch and button 2 should increase it.
If the selected epoch is 123 and user tap > (move forward), then the epoch should increase to 124. If super tap < (move backwards) it should decrease it to 122.
3. To disable or to hide the arrow if its action is not possible.
If there is not possible to move backwards anymore, then < can be gray or another styling that looks like disable or to hide it (you can also use an empty image or another technical solution).
If there is not possible to move backwards anymore, then < can be gray or another styling that looks like disable or to hide it (you can also use an empty image or another technical solution to keep the position).
Same applies for forward button.

**Comment by AndyQus** [comment]
I understood it, I implemented it like this, pictures in the Discord.
