### ISSUE TITLE
Repeat transaction button is missing in the transaction cell

### ISSUE THREAD

**Issue by sallymoc** [qubic/wallet#72]
![image](https://github.com/user-attachments/assets/68a7a445-eefe-480f-b363-7b556fcb0f15)

**Comment by AndyQus** [comment]
@sallymoc this data comes from the archive API and is in another transaction list. I have to look at it.

**Comment by AndyQus** [comment]
![image](https://github.com/user-attachments/assets/3d1d785a-ca3b-4232-9b18-13f75d6b7711)
 new "repeat transactions" function for transactions from the archiver
