### ISSUE TITLE
Send assets button is available for a watch only account

### ISSUE THREAD

**Issue by sallymoc** [qubic/wallet#79]
**Pre-condition**
You have the public id for an account with assets

**Steps**
1. Add a watch only account with assets
2. Go to "Assets"

**Results**
The assets information for the added account is displayed and "Transfer Assets" action is available 

**Expected result**
The assets information for the added account is displayed but "Transfer Assets" action is available because it's a watch only account and trx can't be signed without the private key

**Comment by AndyQus** [comment]
The icon is no longer in the address overview and the asset can no longer be found under assets.
