### ISSUE TITLE
Watch only address is displayed in the source dropdown in the Payment form

### ISSUE THREAD

**Issue by sallymoc** [qubic/wallet#80]
**Pre-condition**
You have added a watch only address

**Steps**
1. Navigate to "Payment" menu option
2. The app display the new payment form
3. Tap on the source field.

Results
The app displays the dropdown with the addresses available in the wallet. Watch only addresses are also included in the list.

**Expected result**
The app displays the dropdown with the addresses available in the wallet but Watch only address are excluded from the list because trx can't be signed without the private key

**Comment by AndyQus** [comment]
The watch-only address is not displayed in the source dropdown list in the payment form
